<title>About</title>
<a name="about"></a>
<div id="about">
	<div id="aboutme">
		<aside id="aboutaside">
			<h1>A little about me</h1>
			<p>I am an aviation professional, a DIY home improvement</p>
			<p>enthusiast, and a maker and fixer. I like pushing myself to my </p>
			<p>limits in endurance sports. I am a graduate student of</p>
			<p>"YouTube University".I am constantly learning, and </p>
			<p>attempting new projects. My favorite projects are web </p>
			<p>design, woodworking, and home upgrades.</p>
		</aside>
		<img src="images/shelf.jpg" alt="image of a live edge oak shelf" id="shelfimage">
	</div>
	<div id="history">
		<h1>How I came about developing websites</h1><br />
		<p>I was a hardware person until the Internet changed everyone's lives.</p>
		<p>I spent around ten years building custom systems, upgrading systems, and troubleshooting.</p>
		<p>Thats when the Internet changed everything. I started designing custom websites for friends.</p>
		<p>I taught myself an assortment of web authoring languages and design practices.</p>
		<p>I have been hooked on both front end and back end web development ever since.</p>
		<p>My goal is to be a PHP guru, and develop highly functional, stunning modern websites to be viewed in all size screens.</p>
	</div>
	<div id="projects">
		<h1>SOME OF MY OTHER PROJECTS</h1>
		<br /><br />
		<div class="aboutimage" id="floor">
			<img src="images/floor.jpg" class="image" id="floor" alt="image of vinyl floor installation">
			<div class="aboutoverlay">
				<p>Luxury vinyl floor installation</p>
			</div>
		</div>
		<div class="aboutimage" id="tile">
			<img src="images/tile.jpg" class="image" id="tile" alt="image of tile shower installation">
			<div class="aboutoverlay">
				<p style=" width:75px; margin-left:70%; margin-top:-5%;">Shower surround installation</p>
			</div>
		</div>
		<div class="aboutimage" id="garden">
			<img src="images/garden.jpg" class="image" id="garden" alt="image of raised bed garden">
			<div class="aboutoverlay">	
				<p style=" width:90px; margin-left:120%;">Raised Bed Gardens</p>
			</div>
		</div>
		<div id="cameraphotos">
			<h1>LIFE THROUGH MY CAMERA LENS</h1>	<br />
			<img src="images/puppy.jpg"alt="image of a puppy">
			<img src="images/paddleboard.jpg" alt="image of a paddleboard">
			<img src="images/river.jpg"  alt="image of VT river">
			<img src="images/sunsettrees.jpg" alt="image of sunset in Westfield MA">
			<img src="images/farm.jpg" alt="image of a farm in Suffield CT">
			<img src="images/sunset.jpg"  alt="image of sunset in Holyoke MA">
		</div>
	</div>
</div>
	





</div>